### PR TITLE
Update to latest Rust

### PR DESCRIPTION
**Pull request by jakub-**

### CODE REVIEW

**Comment by jakub-** [comment]
cc @nrc

**Comment by nrc** [comment]
Thanks for all the changes - they look great! (And sorry it took me a while to get to them - I was away at the weekend).

The file `bin/eg/libhoare.so` shouldn't be here - I'm not sure if you added it or it was there before and you changed it. If you could remove it from the repo, that would be awesome.

You've moved a bunch of files from `src` to `bin`, but they are source files, so I'm not sure why - is it some kind of Cargo-ism?

I thought (but might be wrong, I don't understand Cargo too well) that the Cargo.lock file is generated by Cargo and thus is not necessary to keep in the repo (only Cargo.toml).

**Comment by jakub-** [comment]
@nrc Ah, I didn't mean to bug you on the weekend! :-)

Oops about `libhoare.so` - removed.

I moved the examples to `examples` as opposed to `bin`. I misremember the name of the directory Cargo picks up examples from, it is `examples` indeed. Yes, it is a Cargoism in that `cargo test` will automatically compile files under `examples`. Seems like a sensible change?

You're definitely right about ignoring `Cargo.lock` – this is a library after all. I .gitignored it.

**Comment by jakub-** [comment]
@nrc ping

**Comment by nrc** [comment]
All good, thanks! (And sorry I missed your earlier comment).

**Pull request merged**
